#!/bin/bash
#
HOME_CONDA=1

if [ -f $HOME/.localrc ] ;
then
    . $HOME/.localrc;
fi

set -o vi
export EDITOR='nvim'
export GIT_EDITOR='nvim'

alias vi="nvim"
alias vim="nvim"
alias ls="ls --color"
alias l.="ls -d .*"
alias la="ls -a"
alias ll="ls -al"
alias grep="grep --color"
alias ..="cd .."
alias ...="cd ../.."
alias journalwatch='sudo journalctl -f'
alias nvimrc='nvim ~/.config/nvim/init.vim'
alias docker='sudo docker'
alias pacman='sudo pacman'
alias taif='tail -f'
alias spotify="/usr/bin/spotify --force-device-scale-factor=2"

home_conda() {
    export PATH=$PATH:/home/akail/miniconda3/bin;
    . /home/akail/miniconda3/etc/profile.d/conda.sh;
}

# added by Anaconda3 4.3.1 installer
if [ "$HOME_CONDA" -eq "1" ]; then
    home_conda
fi

export PATH=/home/akail/code/Configs/scripts/:$PATH

# Set the fzf command to use fd instead of find.  Allows leveraging .gitignore in a directory
export FZF_DEFAULT_COMMAND='fd --type f'

#Functions
# This function will extract most common archives      
extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1     ;;
            *.tar.xz)    tar xJf $1     ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       unrar e $1     ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xf $1      ;;
            *.tbz2)      tar xjf $1     ;;
            *.tgz)       tar xzf $1     ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)     echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

startssh() {
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_rsa
}

wiki2df(){
    pandoc -f vimwiki -o $2 $1
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=$HOME/bin:$PATH
