---
- hosts: all
  tasks:
    - include_role:
        name: "andrewrothstein.miniconda"
      vars:
        miniconda_make_sys_default: False

    - include_role:
        name: "andrewrothstein.conda-env"
      vars:
        conda_env_name: '{{item.name}}'
        conda_env_environment: "{{playbook_dir}}/anaconda/{{item.name}}.yaml"
        conda_env_update_if_present: True
      loop:
        - {name: 'base'}
        - {name: 'mlearn'}
        - {name: 'fastai'}
        - {name: 'nlp'}
    - name: Install jupyter lab extensions
      shell: "jupyter labextension install {{item}}"
      become: yes
      loop:
        - "@axlair/jupyterlab_vim"
        - "@jupyterlab/toc"
