---
- hosts: all
  tasks:
  - name: Link configuration files
    file:
      src: "{{playbook_dir}}/files/{{item.src}}"
      dest: "/home/akail/{{item.dest}}"
      state: link
    loop:
      - { src: "condarc", dest: ".condarc" }
      - { src: "gitconfig", dest: ".gitconfig" }
      - { src: "pgcli.conf", dest: ".pgcli.conf" }
      - { src: "scripts", dest: "Apps" }

- hosts: personal
  tasks:
  - name: podman non-root setuid
    become: yes
    lineinfile:
      path: '/etc/{{item.path}}'
      line: 'akail:165536:4096'
      create: yes
    loop:
      - { path: 'subuid'}
      - { path: 'subgid'}

  - name: Add spotify gpg signatures
    shell: curl -sS https://download.spotify.com/debian/pubkey.gpg | gpg --import -
  - name: Nextcloud links
    file:
      dest: "{{ansible_env.HOME}}/{{item.dest}}"
      src: "{{ansible_env.HOME}}/Nextcloud/{{item.src}}"
      state: link
      force: yes
    loop:
      - {src: "Documents", dest: "Documents"}
      - {src: "School", dest: "School"}
      - {src: "Photos", dest: "Pictures"}
      - {src: "Videos", dest: "Videos"}
      - {src: "Work/DST", dest: "DST"}

