---
- hosts: all
  tasks:
  - name: Link configuration files
    file:
      src: "{{playbook_dir}}/files/{{item.src}}"
      dest: "/home/akail/{{item.dest}}"
      state: link
    loop:
      - { src: "condarc", dest: ".condarc" }
      - { src: "gitconfig", dest: ".gitconfig" }
      - { src: "pgcli.conf", dest: ".pgcli.conf" }
      - { src: "scripts", dest: "Apps" }

  - name: podman non-root setuid
    become: yes
    lineinfile:
      path: '/etc/{{item.path}}'
      line: 'akail:165536:4096'
      create: yes
    loop:
      - { path: 'subuid'}
      - { path: 'subgid'}

  - name: Add spotify gpg signatures
    shell: curl -sS https://download.spotify.com/debian/pubkey.gpg | gpg --import -

