---
- hosts: all
  tasks:
  - name: Link git configuration
    file:
      src: "{{playbook_dir}}/../gitconfig"
      dest: /home/akail/.gitconfig
      state: link
  - name: Link postgres cli configuration
    file:
      src: "{{playbook_dir}}/../pgcli.conf"
      dest: /home/akail/.pgcli.conf
      state: link
  - name: Insure ssh directories exist
    file:
      path: '/home/akail/{{item.path}}'
      state: directory
    loop:
      - { path: ".ssh"}
  - name: ssh directory permissions
    file:
      path: '/home/akail/.ssh'
      mode: '0755'
  - name: Link ssh configuration
    file:
      src: "{{playbook_dir}}/../ssh_config"
      dest: /home/akail/.ssh/config
      state: link

