---
- hosts: all
  tasks:
    - name: Projects directory
      file:
        path: '{{ansible_env.HOME}}/Projects'
        state: directory
    - name: github projects
      git: 
        repo: "{{item.repo}}"
        dest: "{{ansible_env.HOME}}/Projects/{{item.path}}"
      loop:
        - {repo: 'https://github.com/akail/kailio', path: "kailio"}
        - {repo: 'https://github.com/akail/homeassistant', path: "homeassistant"}
        - {repo: 'https://github.com/akail/hauberk', path: "hauberk"}
        - {repo: 'https://github.com/akail/Configs', path: "Configs"}
        - {repo: 'https://github.com/akail/scanner', path: "scanner"}
        - {repo: 'https://git.kail.io/akail/ml-projects', path: "ml-projects"}
        - {repo: 'https://git.kail.io/akail/dissertation', path: "dissertation"}
        
